export * from "./setoid";
export * from "./ord";
export * from "./semigroup";
export * from "./monoid";
export * from "./factory";
export * from "./covariant-functor";
export * from "./contravariant-functor";
export * from "./apply";
export * from "./applicative";
